name: actionlint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      go:
        description: 'Go version'
        default: 1.18
        required: false
        type: string

jobs:
  run:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go }}

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: actionlint-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            actionlint-${{ runner.os }}-go-

      - name: Lint
        run: |
          wget https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json
          echo "::add-matcher::actionlint-matcher.json"
          go run github.com/rhysd/actionlint/cmd/actionlint@latest -color
