name: commit

on: [pull_request, workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5.2.0
