name: cover

on:
  workflow_call:
    inputs:
      go:
        description: "Go version"
        default: 1.19
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go }}
          cache: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests with coverage
        run: make coverage

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: profile.out
          if-no-files-found: error
          retention-days: 1

  send:
    runs-on: ubuntu-latest
    needs:
      - run
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: Send coverage
        uses: codecov/codecov-action@v3
        with:
          file: profile.out
