name: govulncheck
on:
  workflow_call:
    inputs:
      go:
        description: "Go version"
        default: "oldstable"
        required: false
        type: string
      timeout-minutes:
        description: "Job timeout in minutes (minimum 15)"
        default: 15
        required: false
        type: number

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1
        with:
          go-version-input: ${{ inputs.go }}
          go-package: ./...
