name: nancy
on:
  workflow_call:
    inputs:
      go:
        description: 'Go version'
        default: "1.21.x"
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go }}
          cache: false

      - name: Get Go environment
        id: go-env
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV

      # Notice: we're using read-only cache.
      #
      # See https://github.com/actions/setup-go/issues/357#issuecomment-1486486358
      - name: Set up cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ env.cache }}
            ${{ env.modcache }}
          key: ${{ runner.os }}-${{ runner.arch }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-go-

      - name: List dependencies
        run: go list -json -m all > go.list

      - name: Run nancy
        uses: sonatype-nexus-community/nancy-github-action@v1.0.3
