name: test
on:
  workflow_call:
    inputs:
      go:
        description: "Go version"
        default: 1.19
        required: false
        type: string

jobs:
  run:
    timeout-minutes: 30
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        flags: [""]
        arch:
          - amd64
        runner:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go:
          - ${{ inputs.go }}
        include:
          - arch: 386
            runner: ubuntu-latest
            go: ${{ inputs.go }}
          - arch: amd64
            runner: ubuntu-latest
            flags: "-race"
            go: ${{ inputs.go }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Run tests
        env:
          GOARCH: ${{ matrix.arch }}
          GOFLAGS: ${{ matrix.flags }}
        run: go test --timeout 30m ./...
